set(headers
    src/Hooks.h
    src/PCH.h
    src/Patchs/HiddenItemsPatch.h
    src/Patchs/SkipEquipController.h
    src/Patchs/UnMapBlock.h
    src/UI/Strings.h
    src/UI/UI_integratedBow.h
    src/Config/Config.h
    src/Config/ConfigPath.h
    src/Persistence/SaveBowDB.h
    src/Input/InputHandler.h
    src/Input/ModeController.h
    src/Input/EventFilter.h
    src/Input/HotkeyDetector.h
    src/Input/InputGate.h
    src/Input/InputState.h
    src/Input/InputTiming.h
    src/Input/ReplayState.h
    src/Input/SyntheticInput.h
    src/State/SessionState.h
    src/State/ChosenBow.h
    src/State/LoadoutRestore.h
    src/DIII/SelectedBowCondition.h
)