set(headers
    src/plugin.cpp
    src/Hooks.cpp
    src/Patchs/HiddenItemsPatch.cpp
    src/Patchs/SkipEquipController.cpp
    src/Patchs/UnMapBlock.cpp
    src/UI/Strings.cpp
    src/UI/UI_integratedBow.cpp
    src/Config/Config.cpp
    src/Persistence/SaveBowDB.cpp
    src/Input/InputHandler.cpp
    src/Input/ModeController.cpp
    src/Input/EventFilter.cpp
    src/Input/HotkeyDetector.cpp
    src/Input/InputGate.cpp
    src/Input/InputState.cpp
    src/Input/ReplayState.cpp
    src/Input/SyntheticInput.cpp
    src/State/SessionState.cpp
    src/State/ChosenBow.cpp
    src/State/LoadoutRestore.cpp
    src/Detours/detours.cpp
    src/Detours/disasm.cpp
    src/Detours/disolx64.cpp
    src/Detours/image.cpp
    src/Detours/modules.cpp
)